spring:
  application:
    name: potato-field
  datasource:
    url: jdbc:h2:mem:potato_field_db  # 'testdb'를 더 명확한 이름으로 변경
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis

server:
  port: 8080

# JWT 설정을 별도의 섹션으로 분리
jwt:
  secret: your_very_long_and_secure_secret_key_here
  expiration: 86400000  # 24 hours in milliseconds